export const GENRES = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Historical Fiction",
  "Horror",
  "Biography",
  "Memoir",
  "Self Help",
  "Non Fiction",
  "Young Adult",
  "Children's Literature",
  "Graphic Novel",
  "Classic Literature",
  "Adventure",
  "Dystopian",
  "Crime",
  "Satire",
  "Poetry",
  "Drama",
  "Philosophical",
  "Science",
  "Travel",
  "Cookbook",
  "Spiritual",
  "Humor",
  "Anthology",
  "Political",
  "War",
];
